volumes:
  db-data:

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ..:/rails-application
    depends_on:
      - db
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
    command: sleep infinity

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
