default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host:     <%= ENV.fetch("DATABASE_HOST") %>

development:
  <<: *default
  database: aibakun_development

test:
  <<: *default
  database: aibakun_test
